### ISSUE TITLE
Adding keyboard shortcuts

### ISSUE THREAD

**Issue by Faalagorn** [jlHertel/adriconf#10]
The program currently lacks any keyboard shortcuts, I'm missing Ctrl+Q for quit in particular, as it's what most programs support and I got used to closing opened windows with a keyboard that way.

**Comment by jlHertel** [comment]
Hi @Faalagorn,
Thanks for the suggestion.
Any other idea of useful keyboards shortcuts?

**Comment by Faalagorn** [comment]
Thanks for the reply! I was thinking about Ctrl+s for saving as well.

I'm not sure about the shortcuts for application menu – `Add new` (Ctrl+n?) and maybe `Remove current application` options (thinking of which, shouldn't they be called the same? i.e. `Add new Application` instead? But I'm digressing). I however have have some issues being unable to add/remove/switch profiles though, with adriconf showing an empty page when switching to anything other than "default" with a `Option mesa_no_error doesn't exist in application Alien Isolation. Merge failed` error – I should report that as a separate issue, but I remembered this extension being relatively new, so this is what probably causes issues and wanted to check how it works with newer version in the meantime.

I wouldn't give any keyboard shortcut for `About` option, as I see software such as arandr doesn't have any keyboard shortcut for it either, especially since it's not needed to be able to quickly access "about" section I guess :).

**Comment by jlHertel** [comment]
I added four shortcuts:

- **Ctrl + S** for saving
- **Ctrl + Q** for exiting
- **Ctrl + N** for adding a new application
- **Ctrl + D** for deleting the current selected application

**Comment by Faalagorn** [comment]
It seems that for some reason Ctrl+Q and Ctrl+S shortcuts doesn't work for me (they don't appear under File menu either). On the other hand, Ctrl+N seems to "work" except I get an error I should probably place as a separate issue tomorrow, after I verify it's not my side or regression, because the same happens when using shortcut or when clicking the option:
```
(adriconf:3070): gtkmm-CRITICAL **: 06:57:56.876: gtkmm: object `newAppDialog' not found in GtkBuilder file.

(adriconf:3070): gtkmm-CRITICAL **: 06:57:56.876: gtkmm: Gtk::Builder: widget `newAppDialog' was not found in the GtkBuilder file, or the specified part of it.

** (adriconf:3070): CRITICAL **: 06:57:56.876: Gtk::Builder::get_widget(): dynamic_cast<> failed.
Add Application dialog is not in glade file!
```
