### ISSUE TITLE
Errors when starting program for Unigine Heaven/Valley

### ISSUE THREAD

**Issue by Faalagorn** [jlHertel/adriconf#11]
When starting adriconf from terminal, I get the following errors, both under `mesa 18.0.3-2` from official Arch repository and `mesa-git 102203.26ddc4f9e1-1` from [unofficial mesa-git arch repository](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#mesa-git).

`Driver 'radeonsi' doesn't support option 'dual_color_blend_by_location' on application 'Unigine Heaven (32-bit)'. Option removed.
Driver 'radeonsi' doesn't support option 'dual_color_blend_by_location' on application 'Unigine Heaven (64-bit)'. Option removed.
Driver 'radeonsi' doesn't support option 'dual_color_blend_by_location' on application 'Unigine Valley (32-bit)'. Option removed.
Driver 'radeonsi' doesn't support option 'dual_color_blend_by_location' on application 'Unigine Valley (64-bit)'. Option removed.`

I also have the following two errors upon starting before these 4 lines appear, kinda similar to #6, although they do not prevent adriconf from starting and applying options to the default profile seemingly
`libGL error: unable to load driver: amdgpu_dri.so
Unable to extract configuration for driver amdgpu`

I'm using Radeon RX 580 8GB with just the Mesa drivers from official Arch Linux repository and RADV (nothing from AMDGPU-PRO or AMDVLK is installed). Kernel is at version 4.16.8, also from official repos which I believe should have enabled AMD DC (Display Code).

**Comment by jlHertel** [comment]
Hi @faalagorn,
I will need to check again, but if I'm not wrong the systemwide drirc file has some applications and options that need to be applied on certain drives to avoid issues.
As they can't provide a separate file for each drive, they include all the options in the file.
When Mesa loads the config the driver simply ignores the options it doesn't recognize.
In the case of adriconf, we are issuing a warning to inform users that the option is not supported by this driver.
I think you can securely ignore this.
In any case, I'm without time this week, but at the weekend I can take a better look and confirm if this is really a issue or if it can be ignored.

**Comment by jlHertel** [comment]
@Faalagorn I checked once again my explanation is correct. Mesa provides a system-wide configuration file which have options that are not valid for all drivers. We are removing these options and issuing a warning. You can securely ignore it.

**Comment by Faalagorn** [comment]
Everything seems to work now, thanks!
