### ISSUE TITLE
Can't load or add new application

### ISSUE THREAD

**Issue by Faalagorn** [jlHertel/adriconf#12]
I briefly mentioned this issue in comments for #10 but they are not related. Also see #11 as the issue happen on the same machine/configuration.

Each time I try to load application profile, checkbox get selected, but an empty window appears in adriconf, where options should be:
![screenshot from 2018-05-14 15-28-57](https://user-images.githubusercontent.com/4951331/40000222-941b93a4-578b-11e8-89ea-7ea1038fe633.png)

Terminal shows the following error every time some application is chosen:
`Option mesa_no_error doesn't exist in application Alien Isolation. Merge failed`

Choosing "default" again shows the regular window back:
![screenshot from 2018-05-14 15-39-24](https://user-images.githubusercontent.com/4951331/40000787-fe5a36d4-578c-11e8-9c9a-4c0b35a5e9a2.png)

**Comment by jlHertel** [comment]
Hi,
This seem to be a problem.
Can you share your configuration file?
It should be at $Home/.drirc

**Comment by Faalagorn** [comment]
Sure, it seems to be quite empty though (I never touched it):
```
<driconf>
  <device screen="0" driver="radeonsi">
    <application name="Default">
    </application>
  </device>
```
I tried removing it as well, but the same error is there.

**Comment by jlHertel** [comment]
@Faalagorn I think the main problem is the way we are currently querying the driver name which is using the libDRM provided name. Mesa uses a hard-coded list to determine the correct driver and doesn't provide any API to query it, so we cannot correctly determine the driver name.
I tried to make a workaround for this with the latest commit.
Please test again with 37c4800bde3fec1c2c48bfb8b0fec10153e3136b
