### ISSUE TITLE
Unable to use the new Save and Quit keyboard shortcuts

### ISSUE THREAD

**Issue by Faalagorn** [jlHertel/adriconf#14]
As of the most recent (`c177182`) commit, I can't use the *Save* and *Quit* keyboard shortcuts. Unlike the *Add new* and *Remove current application*, these shortcuts do not appear next to the name and does not seem to trigger when I hit the combination. I noticed in code that they were added a different way, so that may be a reason, especially since I am not using any standard DE, so that may be something I'm missing (I'm using i3-wm).

* Arch Linux (64-bit)
* Linux 4.16-12
* mesa-git 79fe00efb4
* AMD Radeon RX 580

**Comment by jlHertel** [comment]
This seems to be a duplicate of #13 therefore I will close this one.
If this is a different issue, please feel free to reopen it.

**Comment by Faalagorn** [comment]
Yup, that indeed also solved the missing shortcuts issue, thanks for closing!
