### ISSUE TITLE
Generate RPM packages

### ISSUE THREAD

**Issue by jlHertel** [jlHertel/adriconf#27]
For each Jenkins build we should generate a proper RPM package

**Comment by velurimithun** [comment]
But, we thought to do build an flatpack package right??? Plz check the proposal

**Comment by jlHertel** [comment]
Yeah, I was wondering if we should create both or not.
What do you think?
Do you think is it worth the effort?

Also: I added to the Jenkins build a generation of a deb package, which should give you a good starting point for the flatpack.
