### ISSUE TITLE
Properly handle wayland systems

### ISSUE THREAD

**Issue by jlHertel** [jlHertel/adriconf#36]
Properly support systems that do not have X installed (such as some Wayland systems). Currently, the GLX functions mandate a Xlib display object.

**Comment by jlHertel** [comment]
Hi @velurimithun,
I created this issue so you can reference it in your commits.
I have also removed the TODO section from the README, as I think would make more sense to track them as issues instead.
Feel free to make any comment or suggestion :)

**Comment by velurimithun** [comment]
**Work plan?**
First, a DRIQuerry object [https://github.com/jlHertel/adriconf/blob/master/main.cpp#L11](url) is created.

Shall I rewrite this class checking, if wayland then do EGL stuff else GLX
Or
Write a new class similar to DRIQuerry and if it is wayland use this class?  

_Note:_ We can distinguish display server protocol being used by checking env variable $XDG_SESSION_TYPE

**Comment by jlHertel** [comment]
I would say that the best approach would be to create an interface and then make a new class implementing only the EGL stuff.

Just in case you are in doubt: In c++ you can implement interfaces creating a pure abstract class.

**Comment by jlHertel** [comment]
This has now been solved by #49
