### ISSUE TITLE
Add option to change default config directories

### ISSUE THREAD

**Issue by jlHertel** [jlHertel/adriconf#45]
Mesa allows the user to overwrite the place in which the configuration files are stored, using the environment variables `SYSCONFDIR` and `DATADIR`, respectively for System-Wide configuration and the new admin-wide configuration.
We need to add an option to change this, so we can properly handle systems in which mesa was hand-compiled.

**Comment by HolimaX** [comment]
This is different functionality than https://github.com/jlHertel/adriconf/tree/handle_new_config_locations ?

**Comment by jlHertel** [comment]
Yes.
That other branch refers to handling additional configuration places (The `DATADIR` environment variable mentioned above) that mesa supports, while this issue here is to allow changing at compile time the location in which we read the configurations;

**Comment by HolimaX** [comment]
Hmm, ok, I will try if I will have time as I am now in job opportunity search :( U.S dudes stopped my contract due to some organization restructurization...

**Comment by HolimaX** [comment]
> Yes.
> That other branch refers to handling additional configuration places (The `DATADIR` environment variable mentioned above) that mesa supports, while this issue here is to allow changing at compile time the location in which we read the configurations;

Could you please assign this bug to me?

**Comment by jlHertel** [comment]
@HolimaX In case you are still interested, the directories are used in two places:
Old path: https://github.com/jlHertel/adriconf/blob/master/adriconf/Utils/ConfigurationLoader.cpp#L118
New path: https://github.com/jlHertel/adriconf/blob/master/adriconf/Utils/ConfigurationLoader.cpp#L135
