### ISSUE TITLE
Build with libxml++ 3.0

### ISSUE THREAD

**Issue by City-busz** [jlHertel/adriconf#47]
Appearantly, adriconf builds fine with libxml++ 3.0. 

Please replace libxml++-2.6 with libxml++-3.0 in CMakeLists.txt.

**Comment by jlHertel** [comment]
Not only appearantly, but everything was built with libxml++-3.0
We only use the 2.6 version because its the version available on Ubuntu, therefore the build server can build it.

**Comment by City-busz** [comment]
Maybe allow to build with both versions like this?
https://github.com/manisandro/gImageReader/blob/master/CMakeLists.txt#L91

**Comment by jlHertel** [comment]
Amazing, I never thought about it.
Can you make a pull-request with this?

**Comment by City-busz** [comment]
Done: https://github.com/jlHertel/adriconf/pull/48

**Comment by jlHertel** [comment]
Thanks for your contribution, it's greatly appreciated.
