### ISSUE TITLE
Add option for dri2 renderer

### ISSUE THREAD

**Issue by nmjbhoffmann** [jlHertel/adriconf#50]
On my system (Intel system with a Radeon card on Mesa) I'd like to be able to set the renderer for some applications to dri2 instead of radeonsi, this is mainly for the ability to disable vsync
Eg:
`
<driconf>
    <device screen="0" driver="dri2">
        <application name="GLXgears" executable="glxgears">
            <option name="vblank_mode" value="0" />
        </application>
    </device>
</driconf>
`

**Comment by jlHertel** [comment]
As far as I know, you must pass a valid driver name on the <device> element.
Are you not seeing the option to disable vblank on radeonsi?

**Comment by nmjbhoffmann** [comment]
On my system driver="dri2" is a valid option, adding that to the config gets me ~17000 fps in the gears test instead of 60.

None of the options for the radeonsi driver work on my system ([x.org reference](https://www.x.org/wiki/RadeonFeature/#index2h2)), I have noticed that some games can explicitly force vsync off, but it's very situational, disabling vsync in the options.

I tired creating a profile from the program to remove color channels (which worked) and added the options into the created XML template, though it doesn't seem to make a difference. In my case I wanted to disable vsync for all java applications as a start.

Using dri2 code from above works flawlessly, naturally this isn't optimal as no other radeonsi options would work, and I'm not sure how long dri2 will be supported, but at the same time it would be a good gateway into designing it to work with different drivers.

I'm still trying to figure out the X.Org configs (not an expert), so I might be missing something, but I spent a long time looking for alternatives, and this was the only way I could force vsync off for a particular program without disabling it system wide.

Was really happy to see a GUI for the config, but I can't use it in conjunction with my manual configs as they would naturally get overwritten. This is your baby, this is just a feature request, you can just close the issue if you wish, but figured I'd give feedback.

Perhaps adding a text window with custom config options that can by typed out manually and simply concatenated to the file is an option, I've tested using multiple drivers in the configs and they seem to play nice with each other. 

I'm using Linux Mint 19.1, though been using the dri2 config since Mint 18. Perhaps it's a distro limitation.

I've attached a couple Minecraft screenshots as an example, a little hard to see, but difficult to get a screenshot.
[vsync on](https://imgur.com/a/XWDT3GR) / [vsync off](https://imgur.com/a/f9i93ns)

**Comment by jlHertel** [comment]
This is quite curious, I didn't know you can pass dri2 as a driver name.
Unfortunately I cannot add this now, as the whole architecture of the software floats around the driver that is selected.
For example, when you open adriconf, we discover all GPUs you have on your system, then we ask mesa what are the supported options of each GPU and finally we mix this with the configurations you already have saved on .drirc file.
I find it quite curious that you don't have vblank as an option on your driver. Possible this is not supported by that driver, so when you switch to dri2 you are probably switching to software rendering as well.

As I said, unfortunately I'm not able to fix this, but I can try to at least help you.
Can you share a screenshot of the options you see when executing adriconf?
Also, do you known what driver is being used? R600, radeonsi, etc..

**Comment by jlHertel** [comment]
You also mentioned being on a Intel system with a radeon card.
Does this mean that you have a Intel processor and a radeon GPU, or does this means that you have an integrated Intel GPU and an additional radeon card?

Also, how many monitors do you have? I don't think this can influence, but in any case is worth knowing.

**Comment by nmjbhoffmann** [comment]
No rush naturally, just giving some feedback on your project.
Thanks for the reply.

So, I'm running a Core i7 6700k with an Asus Strix RX580 (Codename Polaris10, sometimes identifies as an RX480 in some programs, but both cards are basically clones of each other) with 2 monitors using HDMI.
The dri2 (Direct Rendering Infrastructure) is definitely a hardware mode (just not a default one), as I can hear the fans spinning up on the GPU, and I doubt CS:GO would be getting over 300fps without it.

You can see driver information in the Minecraft vsync screenshots.

Everything runs using the radeonsi driver by default, though I can specify some applications to run using the dri2 driver, even when the rest of my desktop is running the radeonsi driver.

Here is a hardware info dump taken from the system Info app in Mint, [System Info](https://termbin.com/9wos)

And here are a bunch of screenshots from Adriconf 
[https://imgur.com/a/A7HJQyQ](https://imgur.com/a/A7HJQyQ)
[https://imgur.com/a/KQwaFVf](https://imgur.com/a/KQwaFVf)
[https://imgur.com/a/2Bhjjf6](https://imgur.com/a/2Bhjjf6)
[https://imgur.com/a/1PuwMIG](https://imgur.com/a/1PuwMIG)
[https://imgur.com/a/FtrdwoS](https://imgur.com/a/FtrdwoS)

Note I was able to use the DRI2 renderer on a Sapphire R9 280X in Mint 17 and 18 as well

Hope that helps, let me know if you want any more info.

**Comment by nmjbhoffmann** [comment]
One more thing, the onboard Intel GPU isn't in use at all, it shows up in the PRIME section of Adriconf, but doesn't actually use it when switching to it, I assume I have to plug my monitor into the onboard to actually be able to choose GPU's, which I didn't know you could do, definitely want to play with this feature.

**Comment by jlHertel** [comment]
So far It seems your main GPU doesn't support vblank at all.
What you can do is use a separate profile for Minecraft and run it under the Intel GPU.

Not sure this will work, but here are the steps:
1. Create a separate profile for Minecraft: menu > applications > add new
Then give it a name and the executable
2. Select the newly created profile
3. Under PRIME section select the Intel GPU.
4. You will need to select the application again, as all options will have to be reloaded.
5. Now you will see the vblank option (or at least I hope the Intel driver supports it)
6. Enable it and save
7. Try running Minecraft again and see if the performance changed as desired.

**Comment by jlHertel** [comment]
In the worst case, if this fails, you still have the options to use the dri2 driver only for Minecraft, using the PRIME  configuration.
Unfortunately this is not supported by adriconf, but you can edit the drirc file and change it by yourself.

**Comment by nmjbhoffmann** [comment]
So PRIME allows me to switch to the Intel GPU config, and I created a profile for Minecraft (java), though it seems like it always uses my main GPU (Minecraft shows what GPU it's using), I don't think GPU switching works on desktops quite as well, or at least I need to mess with my hardware config, which I'll try a bit later.

These are the screenshots of the config when the app is set to my Intel GPU
https://imgur.com/a/uMpc0tu
https://imgur.com/imjao8O

Image Quality tab is blank.

Probably going to have to do what I've been doing, though when I use adriconf, it clears all my settings whenever it saves anything, so at the end of the day I'm basically stuck editing the file manually, for now at least.

**Comment by nmjbhoffmann** [comment]
Side note, it seems dri is mesa's main driver, and is supported by Intel and AMD, then they have separate drivers for each specific vendor.
https://dri.freedesktop.org/wiki/

**Comment by jlHertel** [comment]
DRI stands for Direct Rendering Infrastructure.
This is a framework for allowing GL applications to directly render using the hardware, which improves performance.
The Mesa driver should be called mesa, swrast or llvmpipe: https://mesamatrix.net/
In any case, I need to study this particular case and see what can be done to improve the situation.
I will come back to you when I have more data on how we can improve the situation.

Also, sorry for not supporting your current desired feature. I will work on it and try to improve.

**Comment by nmjbhoffmann** [comment]
Thanks man, this project has a lot of potential as there aren't any decent GPU GUI configuration programs out there, one that used to work (and where I got my original settings from) was https://dri.freedesktop.org/wiki/DriConf/

Though it doesn't work on my current system I think due to my desktop environment, and it's a clunky program anyway. Would be really awesome to one day have an all in one app to configure fan speed, clock settings, per application settings and hardware monitoring for GPU's in one place. But I fear that might be far off as there are a lot of considerations to make.

I would give it a crack myself, though I'm a web developer, and learning the dev stack for creating a desktop GUI would take too much of my time, perhaps when work slows down a bit I'll give it a crack.
Otherwise good luck man, really appreciate the work you've done so far.

**Comment by jlHertel** [comment]
This is now open for over a year, and I didn't had time to look into it :(
Given the lack of time, huge effort and low benefit from this, I will close the issue.
If there are more interest in this feature, we can discuss further in a new issue.
