### ISSUE TITLE
"make install" does not install desktop, appdata, icon or json files

### ISSUE THREAD

**Issue by juanitotc** [jlHertel/adriconf#51]
As per the title - in addition, where does adriconf expect to find appdata and json files?

**Comment by jlHertel** [comment]
There are two point in this:
1 - Make should not touch appdata and json files, since those are used exclusively for flatpak
2 - We don't provide icons and desktop for direct install, only for flatpak.

**Comment by juanitotc** [comment]
icons and a desktop file would be useful :)

**Comment by jlHertel** [comment]
Yes, maybe they would be useful, but since the idea is to distribute the software only using flatpak, I don't see much value in adding those.
But if you feel this is really a must have feature, feel free to send a pull request and I will gladly accept it.

**Comment by jlHertel** [comment]
Since no further comment has been made on this, I will close this issue.
Feel free to comment in case you disagree.

**Comment by akien-mga** [comment]
>  1 - Make should not touch appdata and json files, since those are used exclusively for flatpak

AppStream files are actually used by most advanced package managers nowadays, not only flatpak. So for distro packaging, it makes sense to install it.

Same goes for the desktop and icon files.

If you're interested I could likely add an opt-in `ENABLE_PACKAGING` option that installs those files in the expected location for distro packaging.

**Comment by jlHertel** [comment]
@akien-mga I didn't known that distros used the appstream metadata.
If you could create a merge request with the changes I will gladly merge it.

Thanks for pointing this out :)

**Comment by jlHertel** [comment]
Since there is no interest into this, I'm closing it.
