### ISSUE TITLE
adriconf fails with "basic_string::_M_construct null not valid"

### ISSUE THREAD

**Issue by juanitotc** [jlHertel/adriconf#52]
compiling adriconf-1.4 with:

`cmake -LAH -DCMAKE_C_FLAGS_RELEASE="-flto -fuse-linker-plugin -mtune=generic -Os -pipe" -DCMAKE_CXX_FLAGS_RELEASE="-flto -fuse-linker-plugin -mtune=generic -Os -pipe" -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=TRUE ../`

./adriconf
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted

**Comment by juanitotc** [comment]
Sorry, I should have said that this is with x11 and an intel hd4400 haswell gpu

XDG_SESSION_TYPE is unset

If I try "XDG_SESSION_TYPE=X11 adriconf", I get nothing - no output and no errors.

**Comment by juanitotc** [comment]
I also tried in gnome environment with wayland and get the same - no output and no errors.

strace doesn't show any errors and ends with:

exit_group(1)
+++ exited with 1 +++

gdb ends with:

[Inferior 1 (process 30916) exited with code 01]

If I recompile adriconf with -DENABLE_XWAYLAND=TRUE in the gnome environment I get:

Error getting function pointers. LibEGL must be too old

libEGL is from mesa-18.0, but I'm guessing this error is because xwayland does not include egl streams?

**Comment by jlHertel** [comment]
As the message suggests, your libEGL is too old to run under Wayland. Actually I think there is no upstream release with the necessary extension yet, so you will need to wait until a new mesa release is out for the proper Wayland support.

About the error when executing on X11, it could be for a lot of reasons, but since you seem to be compiling a release version, no debug data is included in the binary.
Can you please compile as a debug version and give the output of it?

Also this GPU seems quite old, so possibly its using a legacy driver which doesn't expose any configuration. In any case, adriconf should give a proper error message instead of crashing, so the bug report in greatly appreciated.

Could you also kindly share the amount of physical screens you have? (1 or 2 or more)

**Comment by juanitotc** [comment]
Since adriconf does not crash, I doubt gdb would be of any help, but I compiled a debug version of the latest git with no change - is there any way to get verbose output from adriconf?

I'm not sure what is meant by gpu legacy driver - the i965 driver from mesa-18.0 is in use and the xf86-video-intel driver from Feb 2019 git is also present. The xorg log shows both dri2 and dri3 are enabled.

I am using one screen on a dell e7240 laptop.

I get the same result with wayland (as opposed to xwayland).

**Comment by juanitotc** [comment]
[xorg-log.tar.gz](https://github.com/jlHertel/adriconf/files/2944675/xorg-log.tar.gz)

xorg log attached

**Comment by jlHertel** [comment]
I still think that your driver is not providing any configuration....maybe you compiled it without this option?
In any case, I added some safe-guards to give a better error message if this is the case.

Also, can you please share the output of the following command?
`xdriinfo 0 options`

This should list all configuration options that your current driver supports.

**Comment by juanitotc** [comment]
`$ xdriinfo
Screen 0: i965`

`$ xdriinfo options 0
<driinfo>
<section>
<description lang="en" text="Performance"/>
...
<option name="bo_reuse" type="enum" default="1" valid="0:1">
<description lang="en" text="Buffer object reuse">
<enum value="0" text="Disable buffer object reuse"/>
<enum value="1" text="Enable reuse of all sizes of buffer objects"/>
</description>
</option>
<option name="mesa_no_error" type="bool" default="false">
<description lang="en" text="Disable GL driver error checking"/>
...
</option>
</section>
<section>
<description lang="en" text="Image Quality"/>
...
<option name="precise_trig" type="bool" default="false">
<description lang="en" text="Prefer accuracy over performance in trig functions"/>
...
</option>
<option name="clamp_max_samples" type="int" default="-1">
<description lang="en" text="Clamp the value of GL_MAX_SAMPLES to the given integer. If negative, then do not clamp."/>
</option>
</section>
<section>
<description lang="en" text="Debugging"/>
...
<option name="no_rast" type="bool" default="false">
<description lang="en" text="Disable 3D acceleration"/>
...
</option>
<option name="always_flush_batch" type="bool" default="false">
<description lang="en" text="Enable flushing batchbuffer after each draw call"/>
...
</option>
<option name="always_flush_cache" type="bool" default="false">
<description lang="en" text="Enable flushing GPU caches with each draw call"/>
...
</option>
<option name="disable_throttling" type="bool" default="false">
<description lang="en" text="Disable throttling on first batch after flush"/>
...
</option>
<option name="force_glsl_extensions_warn" type="bool" default="false">
<description lang="en" text="Force GLSL extension default behavior to 'warn'"/>
...
</option>
<option name="force_glsl_version" type="int" default="0" valid="0:999">
<description lang="en" text="Force a default GLSL version for shaders that lack an explicit #version line"/>
...
</option>
<option name="disable_glsl_line_continuations" type="bool" default="false">
<description lang="en" text="Disable backslash-based line continuations in GLSL source"/>
...
</option>
<option name="disable_blend_func_extended" type="bool" default="false">
<description lang="en" text="Disable dual source blending"/>
...
</option>
<option name="dual_color_blend_by_location" type="bool" default="false">
<description lang="en" text="Identify dual color blending sources by location rather than index"/>
...
</option>
<option name="allow_glsl_extension_directive_midshader" type="bool" default="false">
<description lang="en" text="Allow GLSL #extension directives in the middle of shaders"/>
...
</option>
<option name="allow_glsl_builtin_variable_redeclaration" type="bool" default="false">
<description lang="en" text="Allow GLSL built-in variables to be redeclared verbatim"/>
...
</option>
<option name="allow_glsl_cross_stage_interpolation_mismatch" type="bool" default="false">
<description lang="en" text="Allow interpolation qualifier mismatch across shader stages"/>
...
</option>
<option name="allow_higher_compat_version" type="bool" default="false">
<description lang="en" text="Allow a higher compat profile (version 3.1+) for apps that request it"/>
...
</option>
<option name="force_glsl_abs_sqrt" type="bool" default="false">
<description lang="en" text="Force computing the absolute value for sqrt() and inversesqrt()"/>
...
</option>
<option name="shader_precompile" type="bool" default="true">
<description lang="en" text="Perform code generation at shader link time."/>
</option>
</section>
<section>
<description lang="en" text="Miscellaneous"/>
...
<option name="glsl_zero_init" type="bool" default="false">
<description lang="en" text="Force uninitialized variables to default to zero"/>
...
</option>
<option name="allow_rgb10_configs" type="bool" default="false">
<description lang="en" text="Allow exposure of visuals and fbconfigs with rgb10a2 formats"/>
...
</option>
</section>
</driinfo>`

**Comment by juanitotc** [comment]
[xdriinfo.tar.gz](https://github.com/jlHertel/adriconf/files/2948132/xdriinfo.tar.gz)

Output from "xdriinfo options 0" attached

**Comment by juanitotc** [comment]
Note also, that even with the latest commit "XDG_SESSION_TYPE=X11 adriconf" does not produce any output

**Comment by jlHertel** [comment]
This is getting very curious. So it seems your driver is working properly and has the needed options.
When you execute adriconf you said no output is produced. Does this mean that not even an error message is spit out?
The last git commit should have added some error messages.

**Comment by jlHertel** [comment]
Also, the initial error message you posted is an issue with Glib::ustring in which adriconf is passing null as a constructor parameter. Now I just need to figure out where this is and why its happening.

**Comment by juanitotc** [comment]
I confirm that, despite the latest commit, the command "adriconf" results in nothing at all - no error messages or anything else.

Note that the initial error message was a result of XDG_SESSION_TYPE being unset. Is adriconf expecting any other XDG or related variables to be set?

**Comment by jlHertel** [comment]
Now that you asked, yes.
adriconf also expects to find $HOME, and also expects to find the file `/etc/drirc` which is the mesa system-wide file. But now that you asked, I think mesa-developers moved away from `/etc/drirc` so maybe this is the reason. Give me some minutes and I will provide yet another fix.

**Comment by juanitotc** [comment]
/etc/drirc is present

**Comment by jlHertel** [comment]
Just for curiosity, are you running adriconf under X11 or under a Wayland session?

**Comment by juanitotc** [comment]
This is under x11.

I have also tried under wayland (weston) without xwayland, which gives the same lack of output.

Under gnome wayland I get the xwayland old libEGL error.

**Comment by jlHertel** [comment]
Under Wayland it should not work at all, unless you grab latest mesa-git.
Now under X11 I expect it to at least produce some output. But I just found a issue with the way I was handling invalid output from some function in X11.

I made yet another fix, can you please try this latest version?
I still expect it to crash, but it should print a message like this:
`Unable to extract driver name for screen 0`

If this message appears, it indicates that you are missing the configuration query functions in mesa. This is a very tricky case, since those functions are not part of any extension, so is quite hard to check on my end if they are missing.
Also, did you compile mesa by yourself?
If yes, do you mind sharing the parameters used to configure the build?

**Comment by juanitotc** [comment]
I just tried with the latest commit and still get no output.

mesa was compiled with:

`CC="gcc -flto -fuse-linker-plugin -mtune=generic -Os -pipe" CXX="g++ -flto -fuse-linker-plugin -mtune=generic -Os -pipe -fno-exceptions -fno-rtti -D_GLIBCXX_USE_C99_MATH" ./configure --prefix=/usr/local -disable-static --localstatedir=/var --sysconfdir=/etc --enable-texture-float --enable-osmesa --enable-xa --enable-glx-tls --with-platforms="drm,wayland,surfaceless,x11" --with-gallium-drivers="i915,nouveau,r300,r600,radeonsi,svga,swrast,swr" --with-vulkan-drivers="intel,radeon"`

**Comment by jlHertel** [comment]
I think you compiled mesa without driconf support.
I'm not quite sure how to enable it, but on mesa source it is used as `USE_DRICONF`.

**Comment by juanitotc** [comment]
Hmm from ./src/loader/Makefile.in, it looks like -DUSE_DRICONF is the default

**Comment by jlHertel** [comment]
Unfortunately I ran out of easy options, so if you are still trying to make it work, let's try something more hard:
- Compile adriconf in debug mode (`mkdir build-dir && cd build-dir && cmake .. && make`)
- run adriconf inside a GDB session, using this command: `XDG_SESSION_TYPE=x11 gdb ./adriconf`
- Inside the GDB console use the following commands:
1. catch throw
2. run
3. where

Paste the output of ``run` and `where` commands here.

**Comment by jlHertel** [comment]
Aso, I would like to take a minute to apologize for all this inconvenience. It is really an unexpected situation and like you, I'm very frustrated that it doesn't work as expected.
I would also like to thank you for this bug report and your persistence in making it work. Your effort is really appreciated.

**Comment by juanitotc** [comment]
No problem, I like a challenge :)

I just recompiled mesa-18.0 forcing -DUSE_DRICONF and now things seem to work.

As I believe (I could be wrong) USE_DRICONF was enabled by default, could it be that adriconf does not like symlinks?

The reason I say this is that this distro, tinycorelinux, uses squashfs packages loop mounted and symlinked to the root file system. This means that, for example, /etc/drirc is a symlink to /tmp/tcloop/Xorg-7.7-3d/etc/drirc, but recompiling mesa-18 overwrites the symlink with the actual file.

**Comment by jlHertel** [comment]
Interesting findings.
I must admit that I never tried using symlinks, so this is possibly one of the reasons.
The curious part is that there is a specific check to ensure adriconf finds the file. Maybe it was able to find it but not read?

If you are fine with this, I will mark the bug as resolved.

**Comment by juanitotc** [comment]
Don't close the bug just yet - I'll double-check the symlink theory and get back to you

**Comment by juanitotc** [comment]
The issue is not the symlinks, so it seems -DUSE_DRICONF needs to be forced whilst building mesa.

Thanks for the help.
