### ISSUE TITLE
Handle Wayland sessions with empty $XDG_SESSION_TYPE

### ISSUE THREAD

**Issue by juanitotc** [jlHertel/adriconf#55]
As a suggestion, could adriconf automatically detect x11 or wayland rather than having to set $XDG_SESSION_TYPE?

**Comment by jlHertel** [comment]
I'm not sure I got your suggestion.
$XDG_SESSION_TYPE is set by the desktop manager, so you should never set it manually, unless wanting to try adriconf using X11 under Wayland (which will break anyway, so no reason to do this).

Why do you think you should be setting this variable?

**Comment by juanitotc** [comment]
This is a simple distro, tinycorelinux, where simple window managers like flwm, fluxbox, jwm and weston are used without setting $XDG_SESSION_TYPE - adriconf is basically the only app I've come across that requires it to be set in order to work.

**Comment by jlHertel** [comment]
That's quite curious.
`$XDG_SESSION_TYPE` is the most widely suggested way to check for Wayland, but in fact it can happen that it is not being set.
I will investigate other ways to detect Wayland systems and update the code accordingly.

Thanks for the suggestion.

**Comment by jlHertel** [comment]
This has been fixed with latest release `1.5.1`.
I will close this issue, as the system should now be properly detected without relying on the `XDG_SESSION_TYPE`
