### ISSUE TITLE
adriconf doesn't start at all

### ISSUE THREAD

**Issue by Valmar33** [jlHertel/adriconf#58]
Don't know how to describe the issue, except that running `adriconf` does... nothing. It immediately returns.

I'm running Mesa Git and LLVM Git, with an RX580, if that helps.

If you can give me some pointers to start debugging this bizarre issue, that would be excellent.

This issue actually began a very long time ago, but I'd completely forgotten until now. :P

**Comment by jlHertel** [comment]
Are you using latest git code?
There are some fixes there specifically for Radeon users. (I think it's my bad to not have published an update with those yet).
Also, what happens when you try executing it from the command line? Does it give any output?

**Comment by Valmar33** [comment]
Yeah. Using the latest Git.

Executing on the command line gives absolutely nothing, no matter what I do. Even if I enter obviously wrong options like `----`.

Something has been seriously borked for a long time.

**Comment by jlHertel** [comment]
That's curious.
Adriconf usually gives output before initializing other stuff like the GPU.
Given that you compiled it, I will assume that all dependencies are there.

You mentioned that you are using Mesa git. Have you enabled driconf support? This is a requirement for adriconf to work.
Also, can you try compiling adriconf in debug mode? Maybe with the debug symbols it gives a more useful crash info.

**Comment by Valmar33** [comment]
driconf support? Mesa Git doesn't have an option for that, apparently.

Will try with debug symbols.

**Comment by Valmar33** [comment]
Nothing. :(

**Comment by jlHertel** [comment]
Yes, mesa git has an option to compile support for DRIconf.
If I remember correctly, this is disabled by default. I don't remember the name of the option, but I'm 100% sure there is one for this.

Bottom note: DRIconf support in mesa means that it will support reading configuration files, as well as provide some additional gl functions to query the options supported by each driver.

**Comment by Valmar33** [comment]
Hmmm.

How do you compile Mesa?

I'm using https://aur.archlinux.org/packages/mesa-git/, which uses these options: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mesa-git#n94

**Comment by jlHertel** [comment]
I don't compile Mesa. I simple stick with the distribution provided version.
Also, if changing options manually on your ~/.driconf file works, I would say the issue is other.
Can you try to compile adriconf in debug mode, execute and post the output here?
It should be more noise in debug mode.

**Comment by Valmar33** [comment]
I compiled with debug, and there wasn't anything, sadly.

Still no output in the terminal.

What distro do you use, BTW?

**Comment by jlHertel** [comment]
I use Manjaro (which is Arch based).
Can you paste de output of the execution here? The way you are calling the command, up until it crashes.

**Comment by Valmar33** [comment]
https://i.imgur.com/NkJ8s8p.jpg

**Comment by Valmar33** [comment]
Manjaro uses Arch's Mesa package, I think. It's not doing anything special that Mesa Git doesn't do.

**Comment by jlHertel** [comment]
Can you try running it with GDB?
```gdb adriconf
run```

**Comment by Valmar33** [comment]
Reading symbols from /usr/bin/adriconf...
    (No debugging symbols found in /usr/bin/adriconf)

WTF

I compiled it with `-DCMAKE_BUILD_TYPE=Debug`

**Comment by Valmar33** [comment]
`[Inferior 1 (process 10278) exited with code 01]`...

**Comment by jlHertel** [comment]
Can you also show me the output of:
`echo $XDG_SESSION_TYPE`
And finally compile again with the option: `-DENABLE_XWAYLAND`

**Comment by Valmar33** [comment]
`tty`

Compiling with `-DENABLE_XWAYLAND` didn't change anything, either...

**Comment by Valmar33** [comment]
Ah.

`export XDG_SESSION_TYPE=x11` makes it work. :P

**Comment by Valmar33** [comment]
I start my desktop environment with `startx` from a virtual terminal.
