### ISSUE TITLE
Build issues on Slackware 14.2.

### ISSUE THREAD

**Issue by orbea** [jlHertel/adriconf#68]
I would like to add adriconf to slackbuilds.org so that Slackware users can more easily access it, however this requires supporting Slackware stable (`14.2`) which is a bit old now and adriconf does not build for several reasons.

If possible it would be nice if older distros could be supported? Otherwise I can wait until Slackware 15.0 is out which will be when its ready. Please feel free to close this issue if you do not agree with fixing this.

1. The cmake version is too old.
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.8 or higher is required.  You are running version 3.5.2


-- Configuring incomplete, errors occurred!
```
This is easy to workaround.
```
sed -i 's/3.8/3.5.2/' CMakeLists.txt
```
2. The boost version is too old.
```
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1657 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.59.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.60 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:18 (find_package)
```
Again this is potentially easy to workaround.
```
sed -i 's/1.60/1.59.0/' CMakeLists.txt
```
3. libdrm is too old (`2.4.68`).
```
/tmp/SBo/adriconf-1.5.1/adriconf/Utils/DRIQuery.cpp: In member function 'std::map<Glib::ustring, std::shared_ptr<GPUInfo> > DRIQuery::enumerateDRIDevices(const Glib::ustring&)':
/tmp/SBo/adriconf-1.5.1/adriconf/Utils/DRIQuery.cpp:173:80: error: 'drmGetDevices ' was not declared in this scope
     int deviceCount = drmGetDevices2(0, enumeratedDevices, MESA_MAX_DRM_DEVICES);
                                                                                ^
adriconf/CMakeFiles/adriconf.dir/build.make:258: recipe for target 'adriconf/CMakeFiles/adriconf.dir/Utils/DRIQuery.cpp.o' failed
make[2]: *** [adriconf/CMakeFiles/adriconf.dir/Utils/DRIQuery.cpp.o] Error 1
CMakeFiles/Makefile2:154: recipe for target 'adriconf/CMakeFiles/adriconf.dir/all' failed
make[1]: *** [adriconf/CMakeFiles/adriconf.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
This is because `drmGetDevices2` does not exist in `xf86drm.h` and only `drmGetDevices` does.
```
extern int drmGetDevices(drmDevicePtr devices[], int max_devices);
```
This seems easy to solve as well?
```
diff --git a/adriconf/Utils/DRIQuery.cpp b/adriconf/Utils/DRIQuery.cpp
index 802e8e6..3394392 100644
--- a/adriconf/Utils/DRIQuery.cpp
+++ b/adriconf/Utils/DRIQuery.cpp
@@ -170,7 +170,7 @@ std::map<Glib::ustring, GPUInfo_ptr> DRIQuery::enumerateDRIDevices(const Glib::u
     std::map<Glib::ustring, GPUInfo_ptr> gpus;
 
     drmDevicePtr enumeratedDevices[MESA_MAX_DRM_DEVICES];
-    int deviceCount = drmGetDevices2(0, enumeratedDevices, MESA_MAX_DRM_DEVICES);
+    int deviceCount = drmGetDevices(enumeratedDevices, MESA_MAX_DRM_DEVICES);
 
     this->logger->debug(Glib::ustring::compose(_("Found %1 devices"), deviceCount));
 
```
4. gtkmm3 is too old (`3.18.1`).
```
/tmp/SBo/adriconf-1.5.1/adriconf/GUI.cpp: In member function 'void GUI::drawApplicationSelectionMenu()':
/tmp/SBo/adriconf-1.5.1/adriconf/GUI.cpp:214:72: error: no matching function for call to 'Gtk::RadioMenuItem::RadioMenuItem()'
                Gtk::RadioMenuItem *appMenuItem = Gtk::manage(new Gtk::RadioMenuIt
                                                                       ^
In file included from /usr/include/gtkmm-3.0/gtkmm.h:241:0,
                 from /tmp/SBo/adriconf-1.5.1/adriconf/GUI.h:4,
                 from /tmp/SBo/adriconf-1.5.1/adriconf/GUI.cpp:1:
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:123:3: note: candidate: Gtk::RadioMenuItem::RadioMenuItem(Gtk::RadioMenuItem::Group&, const Glib::ustring&, bool)
   RadioMenuItem(Group& groupx, const Glib::ustring& label, bool mnemonic = false)
   ^
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:123:3: note:   candidate expects 3 arguments, 0 provided
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:121:3: note: candidate: Gtk::RadioMenuItem::RadioMenuItem(Gtk::RadioMenuItem::Group&)
   RadioMenuItem(Group& groupx);
   ^
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:121:3: note:   candidate expects 1 argument, 0 provided
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:81:12: note: candidate: Gtk::RadioMenuItem::RadioMenuItem(GtkRadioMenuItem*)
   explicit RadioMenuItem(GtkRadioMenuItem* castitem);
            ^
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:81:12: note:   candidate expects 1 argument, 0 provided
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:80:12: note: candidate: Gtk::RadioMenuItem::RadioMenuItem(const Glib::ConstructParams&)
   explicit RadioMenuItem(const Glib::ConstructParams& construct_params);
            ^
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:80:12: note:   candidate expects 1 argument, 0 provided
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:64:3: note: candidate: Gtk::RadioMenuItem::RadioMenuItem(Gtk::RadioMenuItem&&)
   RadioMenuItem(RadioMenuItem&& src) noexcept;
   ^
/usr/include/gtkmm-3.0/gtkmm/radiomenuitem.h:64:3: note:   candidate expects 1 argument, 0 provided
adriconf/CMakeFiles/adriconf.dir/build.make:426: recipe for target 'adriconf/CMakeFiles/adriconf.dir/GUI.cpp.o' failed
make[2]: *** [adriconf/CMakeFiles/adriconf.dir/GUI.cpp.o] Error 1
CMakeFiles/Makefile2:154: recipe for target 'adriconf/CMakeFiles/adriconf.dir/all' failed
make[1]: *** [adriconf/CMakeFiles/adriconf.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
The `RadioMenuItem` API seems to have changed over time, but I am not sure what should be done here.

3.18.1
https://github.com/GNOME/gtkmm/blob/3.18.1/gtk/src/radiomenuitem.hg#L37

Current master
https://github.com/GNOME/gtkmm/blob/2551b97fc4c6ecb3947fbe7dcdaf564f79b3a18c/gtk/src/radiomenuitem.hg#L37

**Comment by orbea** [comment]
Actually the last build issue is easy too.
```
diff --git a/adriconf/GUI.cpp b/adriconf/GUI.cpp
index 3617831..c8f0858 100644
--- a/adriconf/GUI.cpp
+++ b/adriconf/GUI.cpp
@@ -211,7 +211,7 @@ void GUI::drawApplicationSelectionMenu() {
             Gtk::Menu *driverSubMenu = Gtk::manage(new Gtk::Menu);
             driverSubMenu->set_visible(true);
             for (auto &possibleApp : driver->getApplications()) {
-                Gtk::RadioMenuItem *appMenuItem = Gtk::manage(new Gtk::RadioMenuItem);
+                Gtk::RadioMenuItem *appMenuItem = Gtk::manage(new Gtk::RadioMenuItem(appRadioGroup));
                 appMenuItem->set_visible(true);
                 appMenuItem->set_label(possibleApp->getName());
 
````

**Comment by jlHertel** [comment]
Hi @orbea 
First of all thanks for the interest in the software.
We offer support only to flatpak, as this is easier and a more cross-distribution way to distribute the software.
I understand the wish to make it work with more older software, but at the same time, newer versions of software means more updates, and sometimes even bug-fixes.
Specifically, some days ago a new version of mesa got released (`19.2.0`). This version contains an important bug-fix for adriconf, so soon we are going to start relying on that new functionality, at the same time that we are probably going to break it for anyone with too old libraries.

Finally, if there is any issue with the current flatpak package on Slackware, I'm more than happy to take a look.

**Comment by orbea** [comment]
Bluntly flatpak is completely undesirable and not a solution for my use cases.

I understand that Slackware 14.2 is old at this point, but as I said I am stuck testing it until Slackware 15.0 is out (When its ready).

This means the choices for me are either to workaround/fix these issues or wait until a newer Slackware release. Updating software in Slackware stable will not happen without security issues. If you want to consider this a won't fix I completely understand. :)

> This version contains an important bug-fix for adriconf, so soon we are going to start relying on that new functionality, at the same time that we are probably going to break it for anyone with too old libraries.

Would it be possible to detect the mesa version and use the correct code path for backwards compatibility?

**Comment by jlHertel** [comment]
In this specific case it's possible to detect the newer version with a extension check.

Out of curiosity: why is flatpak undesirable?
It solves exactly this kind of old dependencies issue.

**Comment by orbea** [comment]
> Out of curiosity: why is flatpak undesirable?

Its not a topic I really want to go into in depth, but to be brief many users expect things to work with distro packages or not at all. Its just a very different use case.

**Comment by orbea** [comment]
This seems to be a more correct fix for the 4th issue and adriconf doesn't crash with it.
```
diff --git a/adriconf/GUI.cpp b/adriconf/GUI.cpp
index 3617831..4fb6975 100644
--- a/adriconf/GUI.cpp
+++ b/adriconf/GUI.cpp
@@ -211,7 +211,7 @@ void GUI::drawApplicationSelectionMenu() {
             Gtk::Menu *driverSubMenu = Gtk::manage(new Gtk::Menu);
             driverSubMenu->set_visible(true);
             for (auto &possibleApp : driver->getApplications()) {
-                Gtk::RadioMenuItem *appMenuItem = Gtk::manage(new Gtk::RadioMenuItem);
+                Gtk::RadioMenuItem *appMenuItem = Gtk::manage(new Gtk::RadioMenuItem());
                 appMenuItem->set_visible(true);
                 appMenuItem->set_label(possibleApp->getName());
 
```

**Comment by jlHertel** [comment]
I think that users who choose to use such old software understand that they will not get newer software. If there is any issue with the flatpak package, I'm happy to fix it.
That being said, I will close this as won't fix.

**Comment by orbea** [comment]
I don't mind that you won't look at this, but still suggesting flatpak is just insulting.

**Comment by jlHertel** [comment]
I'm talking from my own experience: when I used debian it was always clear to me that some software would not be available due to the distribution policy.

I'm suggesting flatpak as an alternative to by-pass this restriction at the same time that you maintain the stability that the distro provides.
Why you think it's insulting?
