### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by andersfylling** [jlHertel/adriconf#69]
version: 1.5.1-1
environment: arch linux x86_64 4.19.87-1-lts, i3-gapps

Terminal output:
```
➜ adriconf   
INFO: adriconf running on X11

(adriconf:15504): Gtk-WARNING **: 16:38:59.145: Failed to parse /home/anders/.config/gtk-3.0/settings.ini: Key file does not have group ?Settings?
WARNING: Driver 'nouveau' doesn't support option 'dual_color_blend_by_location' on application 'Unigine Heaven (32-bit)'. Option removed.
WARNING: Driver 'nouveau' doesn't support option 'dual_color_blend_by_location' on application 'Unigine Heaven (64-bit)'. Option removed.
WARNING: Driver 'nouveau' doesn't support option 'dual_color_blend_by_location' on application 'Unigine Valley (32-bit)'. Option removed.
WARNING: Driver 'nouveau' doesn't support option 'dual_color_blend_by_location' on application 'Unigine Valley (64-bit)'. Option removed.
WARNING: Driver 'nouveau' doesn't support option 'adaptive_sync' on application 'gnome-shell'. Option removed.
terminate called after throwing an instance of 'Glib::ConvertError'
[1]    15504 abort (core dumped)  adriconf
```

related: https://github.com/jlHertel/adriconf/issues/11

Edit: Perhaps add a warning in the README?
Edit2: actually a wiki tutorial about this would be nice as I'm struggling a little right now.

**Comment by jlHertel** [comment]
Hi @andersfylling 
First of all, thanks for the interest in this package.
Are you running this using the native package provided in Arch or the flatpak package provided in flathub?
Given the output this looks like an issue with initializing the GUI, but I'm not quite sure.
Can you kindly provide the following information?

- output of `cat $HOME/.drirc`
- How many monitors you have?
- output of running adriconf in debug mode: `VERBOSITY=DEBUG adriconf`
- Are you using the latest updates provided from your distribution? (Worth checking, as there can be a new version of mesa)

About improving the README, I agree that this information should be provided there. I will open a separate issue to track this lack of information. Feel free to add any ideas of things you think are missing/wrong there.

**Comment by jlHertel** [comment]
Also worth mentioning about the current mesa version issue (not affecting Arch, as they use latest versions): https://mastodon.technology/@jlhertel/103248363343162917

**Comment by jlHertel** [comment]
No further data has been provided for this issue, therefore I will close it.
