### ISSUE TITLE
gtest and pkg-config

### ISSUE THREAD

**Issue by etam** [jlHertel/adriconf#7]
In `CMakeLists.txt` gtest is found using `pkg_check_modules`. But the latest release of gtest does not install any pkg-config files (they are in git, but not released yet).

There is support for finding gtest directly in cmake: https://cmake.org/cmake/help/latest/module/FindGTest.html

**Comment by jlHertel** [comment]
I have updated the `CMakeLists.txt` to use the suggested approach.
Thanks for pointing this out :)
