### ISSUE TITLE
Outdated version in About dialog box

### ISSUE THREAD

**Issue by GvMariani** [jlHertel/adriconf#71]
This is really trivial stuff, but whatever...
Even if adriconf is now at release 1.5.1, the in-program About box still says "Version 1.0.0".
Line 616 in GUI.cpp needs a change from:
this->aboutDialog.set_version("1.0.0");
to:
this->aboutDialog.set_version("1.5.1");

**Comment by jlHertel** [comment]
Good catch!
Actually it would be better if we make it dynamic, so we don't need to update it on every new release.
I will take a look on how to do this dynamically.

**Comment by jlHertel** [comment]
This has now been resolved.
