### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [jlHertel/adriconf#73]
I installed gtkmm-3.0-dev, libxml++2.6-dev, and libpci-dev, and when running cmake, I get this error after reaching 100%

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> /home/myname/adriconf/adriconf/Boost_INCLUDE_DIR
>    used as include directory in directory /home/myname/adriconf/adriconf
> /home/myname/adriconf/tests/Boost_INCLUDE_DIR
>    used as include directory in directory /home/myname/adriconf/tests
>
> -- Configuring incomplete, errors occurred!

**Comment by jlHertel** [comment]
Per the error, it seems you are missng the `boost-dev` package.
Can you try to install it and run cmake again?

**Comment by ahmed-elsayed2017** [comment]
I had to install libboost-all-dev to be able to run cmake without errors.

I don't know what this application does. Some people say that this application is the GUI for Mesa, but the settings are complicated for a normal user, and the application is complicated to install. All I wanted is application that can identify the games automatically, and pass them to my dGPU like Switchable Graphics on Windows.

![image](https://user-images.githubusercontent.com/29783425/71781786-5e05c080-2fdb-11ea-90a1-5bd17a05a0e1.png)

**Comment by jlHertel** [comment]
I'm not sure I understood what you meant with `pass them to my dGPU like Switchable Graphics on Windows`.

About installing
---
Compiling by hand is usually hard and error-prone.
If you just want to use it, it's easier to install directly from flathub: https://flathub.org/apps/details/br.com.jeanhertel.adriconf

About the application itself
---
This application is a small GUI tool to set GPU options into applications (think of profiles for each application). It's for advanced users and only exposes options that are already available from the driver (ie: disable error reporting to improve performance, or use multi-threading on the rendering pipeline).
You need to known how to fine-tune a game using such options.

On Windows you have much less options and can control only what the driver thinks is good for the performance (this is easier to use, but not the most optimal).

Unless you are having performance issues with certain games, I think you don't need to switch anything. In general mesa comes with very good defaults and just works.

**Comment by ahmed-elsayed2017** [comment]
> I'm not sure I understood what you meant with `pass them to my dGPU like Switchable Graphics on Windows`.

On Linux I need to use DRI_PRIME=1 to switch manually to my discrete GPU instead of my integrated GPU. On Windows I just open the game, and the driver identifies it, and run it by my discrete GPU automatically, and adds it to Switchable Graphics inside AMD RADEON Settings like this picture:
![image](https://user-images.githubusercontent.com/29783425/71782922-5ac50180-2fe8-11ea-9de7-17ff52f572da.png)

**Comment by jlHertel** [comment]
I think you can achieve the same result using the `device_id` option of mesa.
For this, open adriconf, create a profile for the game you want, and then select the option to `Force Application to use GPU` selecting your discrete GPU.

**Comment by ahmed-elsayed2017** [comment]
I noticed that when I was trying the application, but it is not the same thing as Windows. If I want to get a list of the application that uses Mesa (OpenGL,and Vulkan), how can I do that?

**Comment by jlHertel** [comment]
> If I want to get a list of the application that use Mesa (OpenGL,and Vulkan) on my machine, how can I do that? I just want the filenames. Any help will be highly appreciated.

Mesa is an open source implementation of openGL and Vulkan. Unless you are using closed sources drivers all the graphical applications are using it.
So your question doesn't make much sense for me. Maybe you havê a more specific question?

**Comment by ahmed-elsayed2017** [comment]
When I open any application on my machine, it get stored in the recent opened files, and when I enter a command in terminal, it is stored inside ~/.bash_history

Where does Mesa stores its list of recent opened applications? And how can I get the name of the application during runtime if that is possible?

**Comment by jlHertel** [comment]
As far as I known, mesa doesn't has such functionality.
You can get the application name by opening it and the looking in a task manager or running a command like `ps aux`.
If you have an idea of the name you can also be more specific: `ps aux | grep partOfTheName`

**Comment by jlHertel** [comment]
Additional note: I think there is no easy way to tell if an application is using soft rendering, openGL or Vulkan.
But usually for games they tell you upfront which API they use.
Out of curiosity: which game are you running?

**Comment by ahmed-elsayed2017** [comment]
Lets say that I am running now Doom3.exe which is OpenGL game. How can I know what API it uses, and what its file name?

**Comment by jlHertel** [comment]
If it's an openGL game then it's definetely using openGL.
About it's name, I think the easiest way is to start the game and then use `ps aux | grep doom`. This will give you the correct executable name.
Another way is to look into the executable itself. I suppose you are executing it from somewhere, and this somewhere has either an executable or a script that will call the executable (if it's a script, you need to provide the script name).

**Comment by ahmed-elsayed2017** [comment]
You don't get me, but thanks anyway for trying to help me.

**Comment by jlHertel** [comment]
Sorry for not being able to help further.
If there is anything else I can help, feel free to open another issue.
