### ISSUE TITLE
System-wide configuration reading is broken

### ISSUE THREAD

**Issue by jlHertel** [jlHertel/adriconf#79]
Since an unknown date, mesa is shipping a different format for it's system-wide configuration file `/usr/share/drirc.d/00-mesa-defaults.conf`.
Due to this new format, we are not taking into account any option defined in such files.

We need to fix this to take into account those options again.

Also pertinent question: Does it make sense to really show to users all those workarounds that mesa ships? Maybe we should hide them.

**Comment by clapbr** [comment]
I think hiding those would remove functionality for no real reason, I like to have a GUI to fine tune those workarounds to my needs.

**Comment by jlHertel** [comment]
This has now been fixed by #81
