### ISSUE TITLE
amdgpu_dri.so expected, when it should really want radeon_dri.so or radeonsi_dri.so

### ISSUE THREAD

**Issue by Valmar33** [jlHertel/adriconf#8]
Running ./adriconf gives me this error:

`libGL error: unable to load driver: amdgpu_dri.so`
`Unable to extract configuration for driver amdgpu`

amdgpu is the kernel driver, while radeonsi is the userspace Mesa driver.

**Comment by jlHertel** [comment]
This has already been closed, so I will assume this is not an issue with the latest git code.
If this is still happening, leave me a message and reopen the issue.
