### ISSUE TITLE
adriconf wants obsolete version of libxml++

### ISSUE THREAD

**Issue by v-fox** [jlHertel/adriconf#85]
Build fails on openSUSE now because adriconf rejects libxml++-5.0 and wants 3.0 that was removed.

**Comment by jlHertel** [comment]
This repository is not actively monitored anymore. Next time please consider opening an issue in the official repository [here][1].
I moved the issue [there][2], so I will close this one here.

[1]: https://gitlab.freedesktop.org/mesa/adriconf/
[2]: https://gitlab.freedesktop.org/mesa/adriconf/-/issues/85

**Comment by v-fox** [comment]
@jlHertel When that happens it's customary to archive the github repo, disabling its features and linking to the current one.

**Comment by jlHertel** [comment]
@v-fox Thanks for suggestion, Will definitely do this.
