### ISSUE TITLE
Boost: use 1.64 instead of 1.65 for fedora 27 suport?

### ISSUE THREAD

**Issue by ezickler** [jlHertel/adriconf#9]
Hi,
 i just tried to compile this an found that it needs boost 1.65 but fedora 27 only has boost 1.64. So i just changes it an it worked. So is there any specific feature from 1.65 which is needed? If not i would suggest to reduce the version to make it more accessible on fedora.

**Comment by jlHertel** [comment]
Hi @ezickler, the latest git repository is using Boost 1.60.
Are you using the latest source?

**Comment by ezickler** [comment]
Ohh, my fault.
